---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require:
  - monetize
domains: []
reporters:
  - rubocop
  - require_not_found
require_paths: []
max_files: 5000
